# Generated by Django 4.0.4 on 2024-10-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apreender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='lastSuggestion',
            field=models.DateField(null=True),
        ),
    ]
