# Generated by Django 4.2.10 on 2024-09-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apreender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='lastSuggestion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='nextSuggestion',
            field=models.DateField(),
        ),
    ]
