# Generated by Django 4.0.4 on 2024-09-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apreender', '0002_alter_topic_lastsuggestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='amountSuggest',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='topic',
            name='lastSuggestedProblems',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='learningLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topic',
            name='nextSuggestion',
            field=models.DateField(null=True),
        ),
    ]
