# Generated by Django 4.0.4 on 2024-10-06 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apreender', '0002_alter_topic_lastsuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apreender.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicHtml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(max_length=1000)),
                ('order', models.IntegerField()),
                ('isImage', models.BooleanField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apreender.topic')),
            ],
        ),
    ]
