# Generated by Django 4.0.4 on 2024-09-29 13:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apreender', '0003_alter_topic_amountsuggest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problemStatement',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
