# Generated by Django 4.0.4 on 2024-10-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apreender', '0003_topicimages_topichtml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topichtml',
            name='html',
            field=models.TextField(max_length=5000),
        ),
    ]
