# Generated by Django 4.0.4 on 2024-10-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Apreender', '0005_alter_topichtml_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problemName',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='userPermissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customUserPermissions', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='problemStatement',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customUserSet', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
