# Generated by Django 4.2.10 on 2025-11-06 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apreender', '0006_problem_problemname_user_userpermissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='problemStatement',
            field=models.TextField(blank=True, max_length=1000000, null=True),
        ),
    ]
