# Generated by Django 4.2.10 on 2025-11-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apreender', '0007_alter_problem_problemstatement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topichtml',
            name='html',
            field=models.TextField(max_length=1500000),
        ),
    ]
