# Generated by Django 4.2.10 on 2025-11-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apreender', '0008_alter_topichtml_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topichtml',
            name='html',
            field=models.TextField(max_length=9999999),
        ),
    ]
